### ISSUE TITLE
Missing ../jsoneditor/dist/jsoneditor.min.css when using Vulcanize tool.

### ISSUE THREAD

**Issue by infiman** [Juicy/juicy-jsoneditor#16]
Hi!

First of all thanks a lot for creating this Polymer wrapper around json-editor. Currently, we are using it in one of our projects and seems like we've encountered one problem:

### Steps to reproduce
1. Configure the project to use **Polymer v1**.
2. Build the project using **Vulcanize** tool.
3. Since **Vulcanize** tool follows HTML Imports and <script> tags to inline these external assets into a single page, we will encounter the problem of corrupted import paths. _(After reducing(flattening) all imported assets into the final bundle, all the relative paths which were previously resolved imperatively in the runtime using f.e._ [`Polymer.ResolveUrl.resolveUrl("../jsoneditor/dist/jsoneditor.min.css", script.ownerDocument.baseURI);`](https://github.com/Juicy/juicy-jsoneditor/blob/master/juicy-jsoneditor.html#L54) _won't be able to resolve.)_

#### Live Demo

Let's say we have following structure:
```
app
|___ bower_components
|   |___ jsoneditor
|   |   |___ dist
|   |       |___ jsoneditor.min.css
|   |___ juicy-jsoneditor
|       |___ juicy-jsoneditor.html <=== in the runtime tries to resolve ../jsoneditor/dist/jsoneditor.min.css
|___ elements.html <=== here we are importing juicy-jsoneditor.html
```
Example above works fine till the moment **Vulcanize** tool starts bundling and produces following:
```
app
|___ bower_components
|   |___ jsoneditor
|   |   |___ dist
|   |       |___ jsoneditor.min.css
|   |___ juicy-jsoneditor
|       |___ juicy-jsoneditor.html <=== this page is completely included inside of elements.html page.
|___ elements.html <=== juicy-jsoneditor.html in runtime tries to resolve ../jsoneditor/dist/jsoneditor.min.css but path is already corrupted.
```

### Expected result
Be able to resolve `../jsoneditor/dist/jsoneditor.min.css` dependency on build step using **Vulcanize** tool.

### Actual result
**Vulcanize** tool is not able to detect and include into bundle imperative dependencies which are resolved in the runtime. Right now, `../jsoneditor/dist/jsoneditor.min.css` is not resolved.

### Browsers affected

- [+] Chrome
- [+] Firefox
- [+] Edge
- [+] Safari 9
- [+] Safari 8
- [+] IE 11

_In general, it's not a browser issue. More likely architectural one._

### Screenshot
No styles :(
![image](https://user-images.githubusercontent.com/3742829/34120779-7b12f052-e42f-11e7-81e8-916ee2a204ba.png)

**Comment by infiman** [comment]
Hi, @tomalec! I've provided a fix for this issue in PR https://github.com/Juicy/juicy-jsoneditor/pull/17. Please let me know what do you think.

**Comment by tomalec** [comment]
Hi @infiman! thanks for the report and PR! I'm sorry to respond so late, but I made some comments and proposed few changes at the PR.

**Comment by infiman** [comment]
Please see updates in PR https://github.com/Juicy/juicy-jsoneditor/pull/17
