### ISSUE TITLE
Allow providing raw JSON string in json attribute

### ISSUE THREAD

**Issue by stevenroose** [Juicy/juicy-jsoneditor#21]
The `json` attribute currently requires and object, making it not usable both from raw HTML and from non-JS languages like Dart.

Please support providing raw JSON.

**Comment by tomalec** [comment]
Could you provide a sample?

Check our [to-be](https://github.com/Juicy/juicy-jsoneditor/pull/25) issue template https://jsbin.com/hugamot/1/edit?html,console,output

```html
<juicy-jsoneditor json="{&quot;foo&quot;: 1}"></juicy-jsoneditor>
```

**Comment by tomalec** [comment]
I tried to emphasize it in the readme https://github.com/Juicy/juicy-jsoneditor/pull/28. If that is not your case, please feel free to re-open and provide more details.
