### ISSUE TITLE
Your component is wholely featured in our blog post and it's awesome

### ISSUE THREAD

**Issue by binhbbbb** [Juicy/juicy-jsoneditor#35]
Hi Juicy,

I am Binh from Vaadin. Just want to let you know that we dedicate a whole blog post for your component, [A powerful web component that lets you edit JSON in browser](https://vaadin.com/blog/wcw-26-json-editor). 

Hope that brightens up your day and keep rocking these components!

Binh

**Comment by alshakero** [comment]
Hi Binh!

That's great! Thank you so much 😃
