### ISSUE TITLE
Switch to use josdejong/jsoneditor

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-jsoneditor#4]
`juicy-jsoneditor` currently uses https://github.com/tomalec/jsoneditor/tree/102-onChangeArgumentsBuilt as the JSON tree rendering engine, which is `josdejong/jsoneditor` enhanced to give JSON Patch object as an argument to `change` callback.

As discussed between me and @tomalec on Hangouts, it should be possible to revert to upstream `josdejong/jsoneditor` and use obtain the JSON Patch from a different approach - for example by calling `jsonpatch.compare`

Reverting to use `josdejong/jsoneditor` will give us access to improvements made on regular base in the upstream repo.

In consequence, we will get improved JSON editor in `starcounter-debug-aid`

**Comment by miyconst** [comment]
Done. Needs some testing though. I tested on my local machine, but would be good if someone else could test.

**Comment by tomalec** [comment]
@miyconst `getExpandState` breaks text mode, please check the demo at `index.html`

BTW, I've added `grunt-bump` so to release a new version just run: (`npm install`)
`grunt bump`

**Comment by miyconst** [comment]
Looks like fixed now. Could you check it please?

**Comment by miyconst** [comment]
Ping @tomalec.

**Comment by warpech** [comment]
Currently, bower.json defines dependency on `josdejong/jsoneditor#master`. It should be avoided. 

Use `josdejong/jsoneditor#^4.2.1`

**Comment by miyconst** [comment]
Done.

**Comment by warpech** [comment]
Thanks!
