### ISSUE TITLE
parse error in 'code' mode

### ISSUE THREAD

**Issue by Lukeisme** [Juicy/juicy-jsoneditor#6]
when I using editor's 'code' mode, it cause an json pase error.

```
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'
```

**Comment by tomalec** [comment]
Thanks for reporting, 
I have also added a case for it at demo page http://juicy.github.io/juicy-jsoneditor/

Sorry, that it took that long.
