### ISSUE TITLE
/deep/ is removed from spec

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-jsoneditor#7]
We should substitute the usage of /deep/ in the code, since it was removed from spec: https://groups.google.com/d/topic/polymer-dev/P4WgenEfiAY/discussion

**Comment by warpech** [comment]
Are there any consequences of removing `/deep/`?

**Comment by tomalec** [comment]
I don't think so. My change would narrow the search for focused elements, so the improved performance should be the consequence ;)

I's hard to check it in 100% as this feature was implemented to support reactions to changes made to child nodes of JSON tree which is currently not supported by Polymer + JSONeditor
